In [8]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\avina\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
import torch
torch.__version__

'2.6.0+cu124'

In [3]:
torch.cuda.is_available()

True

In [11]:
# creating pyTorch tensor
import torch
tensor0d=torch.tensor(4)
tensor1d=torch.tensor([1,2,3])
tensor2d=torch.tensor([[1,2,3],[4,5,6]])


In [7]:
tensor1d.dtype

torch.int64

In [6]:
float_tensor=torch.tensor([1.0,2.0,3.0])
float_tensor.dtype

torch.float32

In [9]:
float_tensor=tensor1d.type(torch.float32)
float_tensor.dtype

torch.float32

In [12]:
# common tensor operations
print(tensor2d.shape)

torch.Size([2, 3])


In [13]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [14]:
print(tensor2d.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [15]:
# transpose not same as reshape or view
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [16]:
# tensor multiplication 
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


In [18]:
import torch.nn.functional as F  # functional API for loss functions

# target label (ground truth)
y = torch.tensor([1.0])

# input feature and model parameters
x1 = torch.tensor([1.1])       # input value
w1 = torch.tensor([2.2])       # weight
b = torch.tensor([0.0])        # bias

# linear combination: z = w*x + b
z = w1 * x1 + b

# apply sigmoid to get probability
a = torch.sigmoid(z)

# binary cross-entropy loss between prediction and target
loss = F.binary_cross_entropy(a, y)

# print final loss value
print(loss)

tensor(0.0852)


In [ ]:
# computing gradients via autograd
y= torch.tensor([1.0])
x1=torch.tensor([1.1])
w1=torch.tensor([2.2], requires_grad=True)
b=torch.tensor([0.0], requires_grad=True)

z = w1 * x1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)

# compute gradients of loss w.r.t. parameters
loss.backward()

print(f"Gradient of w1: {w1.grad}")
print(f"Gradient of b: {b.grad}")

AttributeError: partially initialized module 'torch' has no attribute 'types' (most likely due to a circular import)